import type { Metadata } from "next";
import "./globals.css";
import Header from "@/views/components/header";
import Footer from "@/views/components/footer";

export const metadata: Metadata = {
  title: "RickAndMorty",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <head>
            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin={""} />
            <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100..900&display=swap" rel="stylesheet" />
        </head>
        <body>
            <Header />
            {children}
            <Footer />
        </body>
    </html>
  );
}
